# Generated by Django 5.2.4 on 2025-07-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vegetable_quantity_available_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='veggie_images/'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='price_per_kg',
            field=models.FloatField(),
        ),
    ]
