# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vegetable_image_alter_vegetable_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='image',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='image_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
